### ISSUE TITLE
geojson support

### ISSUE THREAD

**Issue by hfstg** [Joolace/leaflet-elementor#1]
Hi,

Any chance of adding support to use geojson to plot areas on a map? 

Thanks

**Comment by Joolace** [comment]
Hi, thanks for the suggestion, it's a function I can try to implement. These days I hope to work on it.

**Comment by Joolace** [comment]
Hey,
GeoJSON is now available: https://github.com/Joolace/leaflet-elementor/releases/tag/1.3.0

If there are problems or you have suggestions, open a new issue
